---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatway
  namespace: microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gatway
  template:
    metadata:
      labels:
        app: gatway
    spec:
      containers:
        - name: gatway
          image: harshyadav02/gateway
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_CLOUD_CONFIG_SERVER_GIT_URI
              value: https://github.com/Harshyadav02/Config-Repo.git
