apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-registry
  namespace: microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-registry
  template:
    metadata:
      labels:
        app: service-registry
    spec:
      containers:
        - name: service-registry
          image: harshyadav02/service-registry
          ports:
            - containerPort: 8761
          env:
            - name: SPRING_CLOUD_CONFIG_SERVER_GIT_URI
              value: https://github.com/Harshyadav02/Config-Repo.git
