---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: service-registry-hpa-deployment
  namespace: microservices
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: service-registry
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
---

