apiVersion: v1
kind: Service
metadata:
  name: service-registry
  namespace: microservices
spec:
  selector:
    app: service-registry
  ports:
    - port: 8761
      targetPort: 8761
  type: ClusterIP
