---
apiVersion: apps/v1

kind: Deployment

metadata:
  name: config-server
  namespace: microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: config-server

  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: harshyadav02/config-server
          ports:
            - containerPort: 8888
          env:
            - name: SPRING_CLOUD_CONFIG_SERVER_GIT_URI
              value: https://github.com/Harshyadav02/Config-Repo.git
