---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: config-server-hpa-deployment
  namespace: microservices
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: config-server
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
---

