apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: microservices
spec:
  ports:
    - port: 3306
      targetPort: 3306
  clusterIP: None # Headless service for StatefulSet
  selector:
    app: mysql
