apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: microservices

spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: harshyadav02/user-service
          ports:
            - containerPort: 8083
          resources:
            requests:
              cpu: "100m" # Minimum CPU required
              memory: "256Mi" # Minimum memory required
            limits:
              cpu: "500m" # Max CPU before throttling
              memory: "512Mi" # Max memory before throttling

          env:
            # Reading Host name form configMap
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_HOST

            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_PORT

            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_DATABASE
              # Database Credentials from Secret
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
